### ISSUE TITLE
Feature Request: Implementation of First Fourth and Last Fourth

### ISSUE THREAD

**Issue by blankster** [thesobercoder/polygon#2]
**Is your feature request related to a problem? Please describe.**
I have an ultrawide monitor with a resolution of 5120x1440. In most cases, it makes sense to use thirds. However, there are instances where it would be useful to use the center half in combination with the first quarter and the last quarter.

**Describe the solution you'd like**
I would appreciate it very much if you could also implement first fourth and last fourth, what would play nicely together with center half.

**Describe alternatives you've considered**
Manual actions :(

**Comment by thesobercoder** [comment]
@blankster Thanks for reporting this issue. I'll try and get a release out next week with the fourths.

**Comment by thesobercoder** [comment]
@blankster I've released v0.4.0 with the all Fourth layout support.

**Comment by blankster** [comment]
Thanks a lot - it works perfect on a ultra-wide monitor 👏🙏
