### ISSUE TITLE
Feature Request: Support of Multiple Hotkeys for an Action

### ISSUE THREAD

**Issue by blankster** [thesobercoder/polygon#3]
**Is your feature request related to a problem? Please describe.**
Typically, I prefer pure keyboard shortcuts, but there are cases where combining them with the mouse can be useful. Currently, I have to choose one or the other.

**Describe the solution you'd like**
Multiple keyboard shortcuts should be assignable to the same action. Ideally, one should also be able to define these shortcuts in the .ini file.

**Describe alternatives you've considered**
-

**Additional context**
I'm currently using the keyboard shortcut CTRL+WIN+NUM1 to CTRL+WIN+NUM3 to arrange windows into thirds. It would be nice to be able to use alternatives to NUM1 through NUM3, including being able to use mouse buttons 1 to 3 (LButton, MButton, RButton). This would be helpful for when your hand is already on the mouse.

**Comment by thesobercoder** [comment]
@blankster I believe you can customize your desired shortcuts in the `INI` file. Please have a look at this [link](https://www.autohotkey.com/docs/v2/KeyList.htm) for all shortcuts available. If you want to mix and match keyboard shortcuts with mouse clicks, you would need to set something like this - `^#LButton[` (<kbd>CTRL</kbd>+<kbd>WIN</kbd>+<kbd>Left Button</kbd>+<kbd>/</kbd>). Hope this helps.
