### ISSUE TITLE
Feature Request: .ini Option to Hide Information Overlay

### ISSUE THREAD

**Issue by blankster** [thesobercoder/polygon#5]
**Is your feature request related to a problem? Please describe.**
When Polygon is used very actively, the information overlay that is shown after each execution of a hotkey, distracts more than it helps.

**Describe the solution you'd like**
It would be great to have a setting in the .ini file to hide the information overlay in general or in a perfect world by a modifier when triggered.

**Describe alternatives you've considered**
Editing out myself from the script and recompile it to an executable.

**Additional context**
I'm using your script together with a "stream deck" as a part of a multi-action trigger. It selects a specific program and then executes a hotkey. For this, it would be great to hide the information overlay.

**Comment by thesobercoder** [comment]
@blankster Thanks for reporting the issue. I have already implemented this feature. Please check the INI file in the report. Just set it to `0` to hide the toast.

https://github.com/thesobercoder/polygon/blob/main/polygon.ini#L25C3-L25C3

**Comment by blankster** [comment]
Nice, that's perfect. Thanks for your feedback 🙂
