### ISSUE TITLE
Bug: Script Doesn’t Work When Window Is Maximized

### ISSUE THREAD

**Issue by blankster** [thesobercoder/polygon#6]
**Describe the bug**
The current script cannot move/resize maximized windows. The information overlay shows that a window was moved, but nothing happens until the window isn't maximized anymore.

**To Reproduce**
1. Maximize a window of an active program
2. Try to use Polygon
3. Information overlay shows that action is executed but nothing happens

**Expected behavior**
Polygon should work as it normally does, especially since using Win+Left or Win+Right also functions as usual. This creates an extra manual step that is actually unnecessary.

**Screenshots**
n/a

**Operating System**
```
OS Name:                   Microsoft Windows 11 Pro
OS Version:                23H2 (10.0.22631.2715)
```

**Additional context**
Various programs open in a maximized state, which interferes with the immediate use of Polygon. Especially if other tools trigger the hotkey of Polygon to move Windows around (in my case, a button press on my Stream Deck), this prevents efficient usage.

**Comment by thesobercoder** [comment]
@blankster This is fixed in v0.5.0. Please get the latest version and try it out.

**Comment by blankster** [comment]
@thesobercoder Thanks for fixing this 🙏 I can confirm it works now for the most applications.

Exceptions:
* When "Remote Desktop" is in full screen, it doesn't work.
* Applications that need admin permissions - I assume Polygon would elevate rights for this too. It drops in such cases an error:

`Error on line 422: (5) Access is denied.`

**Comment by thesobercoder** [comment]
@blankster Can you try running Polygon with admin rights and see if that resolves the problem? I've intentionally kept Polygon to run with the least privilege possible by default.
